name: k6 load test

on:
  pull_request:
  schedule:
    - cron: "0 5 * * *" # daily at 05:00 UTC (~midnight ET)
  workflow_dispatch:

jobs:
  k6:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ http://128.2.220.232:4567/ }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up k6
        uses: grafana/setup-k6-action@v1
        with:
          version: v0.49.0

      - name: Run k6
        run: |
          k6 run --summary-export k6-summary.json k6-tests/loadtest.js

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: k6-results
          path: k6-summary.json
